services:
  twingate-connector:
    image: twingate/connector:1.90.0
    container_name: twingate-connector
    restart: unless-stopped
    network_mode: host
    environment:
      TWINGATE_NETWORK: ${network}
      TWINGATE_ACCESS_TOKEN: ${access_token}
      TWINGATE_REFRESH_TOKEN: ${refresh_token}
      TWINGATE_LOG_ANALYTICS: v2
      TWINGATE_LOG_LEVEL: 3

  dozzle-agent:
    image: amir20/dozzle:v10.6.11
    container_name: dozzle_agent_tg
    restart: unless-stopped
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
    environment:
      DOZZLE_HOSTNAME: twingate-connector
