---
all:
  hosts:
    homepage:
      ansible_host: 10.24.10.10
    immich:
      ansible_host: 10.24.10.13
    monitoring:
      ansible_host: 10.24.10.9
    paperlessngx:
      ansible_host: 10.24.10.12
    rustfs:
      ansible_host: 10.24.10.6
    technitium-dns1:
      ansible_host: 10.24.10.7
    traefik:
      ansible_host: 10.24.10.8
    vaultwarden:
      ansible_host: 10.24.10.11
