---
all:
  hosts:
    homepage:
      ansible_host:
    immich:
      ansible_host:
    monitoring:
      ansible_host:
    paperlessngx:
      ansible_host:
    rustfs:
      ansible_host:
    traefik:
      ansible_host:
    vaultwarden:
      ansible_host:
