---
all:
  hosts:
    homepage:
      ansible_host:
    immich:
      ansible_host:
    monitoring:
      ansible_host:
    paperlessngx:
      ansible_host:
    rustfs:
      ansible_host:
    technitium-dns1:
      ansible_host: 10.24.10.7
    traefik:
      ansible_host: 10.24.10.8
    vaultwarden:
      ansible_host:
