---
- name: "Crear directorios del stack de twingate2"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "{{ stack_base_path }}/twingate2"

- name: "Copiar docker-compose de twingate2"
  ansible.builtin.copy:
    src: "{{ compose_files_path }}/twingate2/docker-compose.yml"
    dest: "{{ stack_base_path }}/twingate2/docker-compose.yml"
    mode: "0644"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  notify: "Recrear stack de twingate2"

- name: "Descifrar archivo .env de twingate2"
  ansible.builtin.command: "sops -d {{ compose_files_path }}/twingate2/.env"
  delegate_to: localhost
  become: false
  register: deploy_twingate2_env
  changed_when: false
  no_log: true

- name: "Escribir archivo .env descifrado"
  ansible.builtin.copy:
    content: "{{ deploy_twingate2_env.stdout }}"
    dest: "{{ stack_base_path }}/twingate2/.env"
    mode: "0600"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  no_log: true
  notify: "Recrear stack de twingate2"
