services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle_webserver
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dozzle_data:/data
    ports:
      - 8080:8080
    environment:
      DOZZLE_HOSTNAME: monitoring
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_REMOTE_AGENT: "10.24.10.6:7007,\
        10.24.10.7:7007,\
        10.24.10.8:7007,\
        10.24.10.10:7007,\
        10.24.10.11:7007,\
        10.24.10.12:7007,\
        10.24.10.13:7007,\
        10.24.10.14:7007"
      # rustfs,dns1-technitium,traefik,monitoring,homepage,vaultwarden,filebrowser,immich,twingate
