---
user: ENC[AES256_GCM,data:xCgMOvCPhmmGLUvC/A==,iv:KKX35N9UdU8aZFuSZJcCgiU1xVBGuVdQjd7D9t8nilo=,tag:Ix+vmG1/T7CTzMpS2cP1kw==,type:str]
user_password: ENC[AES256_GCM,data:YNYManaeBFDv5w==,iv:Iw7001icykeP5MDvPcHTuVelf+m+xWmJZ5Y8dMAls4g=,tag:BDBWggtIH2kmAJyXpc7mrg==,type:str]
base_path: ENC[AES256_GCM,data:ckvRAEkg3tfM6ieKe4VnFrPKkLOBQX6giogZ,iv:WgVQTLvApLfAtVS98KtgKKacrMQe6l/jPlS/ZvvixtY=,tag:NWF32AWVESpdzGrkKMqk2A==,type:str]
ssh_key:
  ENC[AES256_GCM,data:4pJhHPMBwTaRfhE3JjUk4kEUt8po1KAlEgD8ewngxcnI8Ck3NanmWQo6uBuN/sI9A+BTWjwIqz0VTiH8ziRThf7zyEIEkInJyrkTLJpyBAaDY/MzZYNgdeFAebR42Ehr9H2uSrcUcA==,iv:v+urS5aAj5rnQ48/m72iUfRNbJ4HgtYUzJMH+ewoNCo=,tag:dAfXDMKpTssXHOjFsuvdaw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwT29ua2FucDMvblBRdjA0
        QUtGN29CNHExazJ2cEJXVThLeGg5L2dCWDNNClFoV2NzOC9RTjlQRmw4VGYxSXQv
        V1VCWWJqZ2oraGMySUhFZGFZWE5xY3MKLS0tIFV2YkphQlhpVDZHVGxxVUpEL3FZ
        RFdvakY0YjdxTXpuVVhLTEVLMHVYMncKtcFkFSyw77urJgIdykTHZAdEE9z4OxCl
        qtgsrZWTqYI25cVHTY+zqn6397FUqEEAem0iioHNHBD2tazxF0mGYQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16udccp9tk379p58t0ytj5uepqjp5n0tza5q95pz2ugff55tdy4zsuj87vy
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWN0J6cU9wc29uUm1yd0JT
        ZVkrQ2I3TU9veWFQQ2J4RkgvL0NhM3RhdUNvCnpCRFFrbDgzdnErSjd1V01NN3Br
        Y0pPaTc5UHlpd2lIeTNVaHRqK2kxRFkKLS0tIDYwVzZoNElKcGZxRTJKKzB6dkUx
        VkVhWUdTWlR6a0J2WXhuWXdlK3IvVGMKMuKJLbbndJUsVNsC2/JzUW465UEoGrYz
        HqVarbfEG7oBrXGvYkM/BFSMH/5MvS02exL+hwCmzWL4JeKBGxLIew==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17wvygazh5w2ds4xvksmd35rz2geezwgq5papqh04rj8wlhfx7ajqvmjeny
  lastmodified: "2026-06-20T01:35:04Z"
  mac:
    ENC[AES256_GCM,data:Ih4JdLzCEqU0FmDvbQETkns/iC1Awvy9EIPi8U+kUcPZpVbsR8QPsO3cMTdgFxP723zzpzOmxq8urDv/0u3sbB7roTuxDeSQ/9rAoMwcrpxGY7srjuXHzWTDMpHN5Vffe7dY/38RCg7rhM+FR4Bv50wBYtkWyV2YTrPz+WHR5Ww=,iv:bMlyzTjL86lgxzPQ8IR6tmj5Rj0XbZQbdhrGrBe88To=,tag:qcJG88KVYNUvcdJVkZ4AQA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
