user: ENC[AES256_GCM,data:p5q9eYemk0lRsuuflQ==,iv:23Ge6Eozg39/mPR0RBTsA7MItZ83E24jYEeLPsjIXiU=,tag:g/gi8QO5x2apaOIRDzpHlw==,type:str]
user_password: ENC[AES256_GCM,data:UiusIkY2RyY8ZA==,iv:6ZKFRjnMzIfRUokUiBoT1UJ1sJD7naQZzjCE5oXn1VE=,tag:5Kft5UDo88goo9Cve4SrCA==,type:str]
base_path: ENC[AES256_GCM,data:4ateQMDWi1KcyL11gh0VWKz58dDaIxpryukB,iv:Pj/WAT+wr2aI/dq1FtpNFaExlF6By8uwCp6fbOKpDjs=,tag:QSFOH+/H5F6d3LPsAczx1w==,type:str]
ssh_key: ENC[AES256_GCM,data:kWB50usuU/ryvZAolt3hEdgnFjAcbYFQVavpCXxu6p7sGa9dPWrO4nUSdDgQXDvoJdbPHLGZnZZB1X1e32ZIh/4A4bt+Z/QzgYF5KA6f6uSWa0iHY0DjYasP25Qk2Qa6kZbrn+iULw==,iv:VoOTAqTCv3Vrq82WYO77LKfxNMIgizjbphr5yG6acl0=,tag:2cDDZPyNuZ6kGQ+cc6MqPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtN0dET3BzbXpoUGsxamZS
            TTJQMTNra0NDYjNueitKY0dOUCt5b3NScEZJCjN3OVEvUUpHQWVQQlh0ZUkvYWdY
            OCsrRnNBWDZHZTRvZ1pwWFVkRWZTd00KLS0tIHNZVTFYVGx3M2JXUmxIZ3VNVVds
            by9jTTQxeWFiNTdpVkNKbFUrdzhRUFEK41pujtAaTVd7kRsoL82cOPrz/t/1orvR
            7iEUeZiuDHhrc5kZpBPXJo5hq0nxExZ+02d23/YOmk53Oswf0zIOuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16udccp9tk379p58t0ytj5uepqjp5n0tza5q95pz2ugff55tdy4zsuj87vy
    lastmodified: "2026-06-19T07:42:32Z"
    mac: ENC[AES256_GCM,data:620Vnja++0Tzzqvm3NsL3R6ff0wMlAsRzd9/W04nrz2WA26QNWtTNyMuzMm4/2jVcBCQ5d58p8mKyKk2fNNiVihMK1GlLqo7R+P7U7q1G86jQ/A6wgS3ung2EfQWG09YhDpasohNcWO0VlXL9eQQ8SKeklUdM1EIljrFk+geaj8=,iv:we1xWtxdYnx1lchGwnUxZCl6Yv+y9kWinW3Qb6ySIMo=,tag:kgP1iL6QsE1r7Wzk5VFORQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
