user: ENC[AES256_GCM,data:ZB8rRTE6489Me7Cxcg==,iv:ayotbtqTgT53PyaCZEAM/heYfO09A1q0tj5mSfC3e8g=,tag:hY1i1Vgu2L3+nQuTc4CJVQ==,type:str]
user_password: ENC[AES256_GCM,data:l/2p5i+BbRtMag==,iv:qLhzlinxgX1em3Q9RuKL2YsJQZGCp+lNeye8DTbcPAw=,tag:0zOJ68ovFw2vYG59POEC4A==,type:str]
base_path: ENC[AES256_GCM,data:L/7hEojTwCz313rbAUuzB/dkUjGell1lZ2YV,iv:8LQX2XBk12eeWRRVaDr9OUcp3HWsyMcJ42jiid0x8B4=,tag:XeSJxWwPZ+KOLUGiydIo6A==,type:str]
ssh_key: ENC[AES256_GCM,data:nTcCUVrOwK0fYDbTzV4D9o+7el5XC3kqp8m4qCoJnt1wgt8BOIA+JnZdLBB2x4XV6S0h3Ed+2MkrivQN5L0lEditjw5z3X7o6y1R69xf1r9xgS5RjiwOr4v1bVHIjwFuZaPTClggOQ==,iv:/c+3j2Ewuu+fJas9hK/SbbNs27kNdwqtR/urmhMyM1I=,tag:J2f09u6kJn+r8WpUt3ygBA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFa0c5QnB3UEpaTTI1Nkhn
            SExxaExZZVNkUFg2cXF5S08xMjdwaVh0cFNNCmtWamVZWWlDWEdCaG1TQVoxanZh
            SlJ2STBjRlN6OG9lazYycVZibC9zSVkKLS0tIGM5REgrQjZ1SExZK2JPWlloV2xt
            Ny8zRkV6d0s3OGlic25BRGZUekFYbTQKNa6uh8JXfYwgz+tBC5M3nq0m7gNsMLfo
            5+0jLtfvqcxs0wn16BxD8Hp1ifFb/fh0+Wk8kmEUoJBkfkBUL4Q/eA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16udccp9tk379p58t0ytj5uepqjp5n0tza5q95pz2ugff55tdy4zsuj87vy
    lastmodified: "2026-06-19T19:25:47Z"
    mac: ENC[AES256_GCM,data:7hY+WFtU4NlFfvXicYPt3E0LOUhFPntHAUGf2JH70/OREhtUzm0IXZAsusbW374EN/QMMlkAHtip83X1slpd/SipHum13tR5E8E2WTitOYjnJk+QH2bYag4Z55r/u5PURsU92oZfdhoZNljTS7G0Dm1xXryJ9DHtQqmBp8VBZA8=,iv:GKWP9Q9w8+728+PJYCe6Vq5xtnog6ONcihEdRUZ/4VM=,tag:kc057M4FAvqiuVY4guzkgw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
