---
- name: "Crear directorios del stack de paperlessngx"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  loop:
    - "{{ stack_base_path }}/paperlessngx"
    - "{{ stack_base_path }}/paperlessngx/redisdata"
    - "{{ stack_base_path }}/paperlessngx/pgdata"
    - "{{ stack_base_path }}/paperlessngx/data"

- name: "Copiar docker-compose de paperlessngx"
  ansible.builtin.copy:
    src: "{{ compose_files_path }}/paperlessngx/docker-compose.yml"
    dest: "{{ stack_base_path }}/paperlessngx/docker-compose.yml"
    mode: "0644"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  notify: "Recrear stack de paperlessngx"

- name: "Descifrar archivo .env de paperlessngx"
  ansible.builtin.command: "sops -d {{ compose_files_path }}/paperlessngx/.env"
  delegate_to: localhost
  become: false
  register: deploy_paperlessngx_env
  changed_when: false
  no_log: true

- name: "Escribir archivo .env descifrado"
  ansible.builtin.copy:
    content: "{{ deploy_paperlessngx_env.stdout }}"
    dest: "{{ stack_base_path }}/paperlessngx/.env"
    mode: "0600"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  no_log: true
  notify: "Recrear stack de paperlessngx"
