---

- name: "Despliegue de Traefik"
  hosts: traefik
  become: true
  tags: ['traefik']

  tasks:
    - name: "Traefik | Crear directorios de configuracion"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: erickcastillo
        group: erickcastillo
        mode: '0755'
      loop:
        - "/home/erickcastillo/homelab/traefik/config"
        - "/home/erickcastillo/homelab/traefik/dynamic"

    - name: "Traefik | Descifrar cf-token (Local)"
      ansible.builtin.command: "sops -d ../../traefik/config/cf-token"
      delegate_to: localhost
      become: false
      register: traefik_cf_token
      changed_when: false

    - name: "Traefik | Escribir cf-token descifrado"
      ansible.builtin.copy:
        content: "{{ traefik_cf_token.stdout }}"
        dest: "/home/erickcastillo/homelab/traefik/config/cf-token"
        mode: '0600'
        owner: erickcastillo
        group: erickcastillo

    - name: "Traefik | Copiar YAMLs de configuracion estatica"
      ansible.builtin.copy:
        src: "../../traefik/config/traefik.yml"
        dest: "/home/erickcastillo/homelab/traefik/config/traefik.yml"
        mode: '0644'
        owner: erickcastillo
        group: erickcastillo

    - name: "Traefik | Copiar YAMLs de configuracion dinamica"
      ansible.builtin.copy:
        src: "../../traefik/dynamic/"
        dest: "/home/erickcastillo/homelab/traefik/dynamic/"
        mode: '0644'
        owner: erickcastillo
        group: erickcastillo

    - name: "Traefik | Copiar docker-compose"
      ansible.builtin.copy:
        src: "../../traefik/docker-compose.yml"
        dest: "/home/erickcastillo/homelab/traefik/docker-compose.yml"
        mode: '0644'
        owner: erickcastillo
        group: erickcastillo

    - name: "Traefik | Descifrar .env (Local)"
      ansible.builtin.command: "sops -d ../../traefik/.env"
      delegate_to: localhost
      become: false
      register: traefik_env
      changed_when: false

    - name: "Traefik | Escribir .env descifrado"
      ansible.builtin.copy:
        content: "{{ traefik_env.stdout }}"
        dest: "/home/erickcastillo/homelab/traefik/.env"
        mode: '0600'
        owner: erickcastillo
        group: erickcastillo

    - name: "Traefik | Levantar contenedor"
      ansible.builtin.command: "docker compose up -d --force-recreate --remove-orphans"
      args:
        chdir: "/home/erickcastillo/homelab/traefik"
      changed_when: true
