---
# ------------------------------------------------------------------------------
# Despliegue de Servicios (GitOps Flow)
# ------------------------------------------------------------------------------
- name: "DESPLIEGUE: Traefik (Core Proxy)"
  ansible.builtin.import_playbook: deploy_traefik.yml

- name: "DESPLIEGUE: Stack de Observabilidad"
  ansible.builtin.import_playbook: deploy_monitoring.yml

- name: "DESPLIEGUE: Vaultwarden (Seguridad)"
  ansible.builtin.import_playbook: deploy_vaultwarden.yml

- name: "DESPLIEGUE: Paperless (Gestión Documental)"
  ansible.builtin.import_playbook: deploy_paperlessngx.yml

- name: "DESPLIEGUE: Immich (Media Server)"
  ansible.builtin.import_playbook: deploy_immich.yml

- name: "DESPLIEGUE: Homepage (Dashboard)"
  ansible.builtin.import_playbook: deploy_homepage.yml
