---

- name: "Despliegue de Paperlessngx"
  hosts: paperlessngx
  become: true
  vars_files:
    - vars/secrets.yml
  tags: ['paperlessngx']

  tasks:
    - name: "Copiar docker-compose"
      ansible.builtin.copy:
        src: "../../paperlessngx/docker-compose.yml"
        dest: "{{ base_path }}/paperlessngx/docker-compose.yml"
        mode: '0644'
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Descifrar archivo .env"
      ansible.builtin.command: "sops -d ../../paperlessngx/.env"
      delegate_to: localhost
      become: false
      register: paperless_env
      changed_when: false

    - name: "Escribir archivo .env descifrado"
      ansible.builtin.copy:
        content: "{{ paperless_env.stdout }}"
        dest: "{{ base_path }}/paperlessngx/.env"
        mode: '0600'
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: "Levantar contenedor"
      ansible.builtin.command: "docker compose up -d --force-recreate --remove-orphans"
      args:
        chdir: "{{ base_path }}/paperlessngx"
      changed_when: true
