---

- name: "Despliegue de Monitoring"
  hosts: monitoring
  become: true
  tags: ['monitoring']

  tasks:
    - name: "Monitoring | Crear directorio dozzle_data"
      ansible.builtin.file:
        path: "/home/erickcastillo/homelab/monitoring/dozzle_data"
        state: directory
        owner: erickcastillo
        group: erickcastillo
        mode: '0755'

    - name: "Monitoring | Descifrar users.yml (Local)"
      ansible.builtin.command: "sops -d ../../monitoring/dozzle_data/users.yml"
      delegate_to: localhost
      become: false
      register: users_yml
      changed_when: false

    - name: "Monitoring | Escribir users.yml descifrado"
      ansible.builtin.copy:
        content: "{{ users_yml.stdout }}"
        dest: "/home/erickcastillo/homelab/monitoring/dozzle_data/users.yml"
        mode: '0644'
        owner: erickcastillo
        group: erickcastillo

    - name: "Monitoring | Copiar docker-compose"
      ansible.builtin.copy:
        src: "../../monitoring/docker-compose.yml"
        dest: "/home/erickcastillo/homelab/monitoring/docker-compose.yml"
        mode: '0644'
        owner: erickcastillo
        group: erickcastillo

    - name: "Monitoring | Levantar contenedor"
      ansible.builtin.command: "docker compose up -d --force-recreate --remove-orphans"
      args:
        chdir: "/home/erickcastillo/homelab/monitoring"
      changed_when: true
