---
- name: "Desplegar traefik"
  ansible.builtin.import_playbook: deploy/deploy_traefik.yml

- name: "Desplegar technitium"
  ansible.builtin.import_playbook: deploy/deploy_technitium.yml

- name: "Desplegar homepage"
  ansible.builtin.import_playbook: deploy/deploy_homepage.yml

- name: "Desplegar monitoring"
  ansible.builtin.import_playbook: deploy/deploy_monitoring.yml

- name: "Desplegar vaultwarden"
  ansible.builtin.import_playbook: deploy/deploy_vaultwarden.yml

- name: "Desplegar filebrowser"
  ansible.builtin.import_playbook: deploy/deploy_filebrowser.yml

- name: "Desplegar rustfs"
  ansible.builtin.import_playbook: deploy/deploy_rustfs.yml

- name: "Desplegar immich"
  ansible.builtin.import_playbook: deploy/deploy_immich.yml

- name: "Desplegar twingate"
  ansible.builtin.import_playbook: deploy/deploy_twingate.yml
