- "":
    - Tailscale:
        - icon: tailscale
          href: https://login.tailscale.com/admin/machines
    - GitHub:
        - icon: github
          href: https://github.com/kiddyeyo
    - Cloudflare:
        - icon: cloudflare
          href: https://dash.cloudflare.com/e444dc92205e38550492e46722cd4c4e/home/overview
