services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      # Mount the current directory as config folder
      - ./:/app/config
    environment:
      TZ: America/Hermosillo
      HOMEPAGE_URL: https://homepage.infra.sintaq.net
      HOMEPAGE_CSRF_TRUSTED_ORIGINS: https://homepage.infra.sintaq.net
      HOMEPAGE_ALLOWED_HOSTS: homepage.infra.sintaq.net,homepage
      HOMEPAGE_TRUSTED_PROXIES: traefik
      PUID: ${PUID}
      PGID: ${PGID}
      HOMEPAGE_VAR_PVE_USERNAME: ${HOMEPAGE_VAR_PVE_USERNAME}
      HOMEPAGE_VAR_PVE_PASSWORD: ${HOMEPAGE_VAR_PVE_PASSWORD}
      HOMEPAGE_VAR_PBS_USERNAME: ${HOMEPAGE_VAR_PBS_USERNAME}
      HOMEPAGE_VAR_PBS_PASSWORD: ${HOMEPAGE_VAR_PBS_PASSWORD}
      HOMEPAGE_VAR_TRUENAS_KEY: ${HOMEPAGE_VAR_TRUENAS_KEY}
      HOMEPAGE_VAR_TRUENAS_USERNAME: ${HOMEPAGE_VAR_TRUENAS_USERNAME}
      HOMEPAGE_VAR_TRUENAS_PASSWORD: ${HOMEPAGE_VAR_TRUENAS_PASSWORD}
      HOMEPAGE_VAR_TRAEFIK_USERNAME: ${HOMEPAGE_VAR_TRAEFIK_USERNAME}
      HOMEPAGE_VAR_TRAEFIK_PASSWORD: ${HOMEPAGE_VAR_TRAEFIK_PASSWORD}
      HOMEPAGE_VAR_TECHNITIUM_KEY: ${HOMEPAGE_VAR_TECHNITIUM_KEY}
      HOMEPAGE_VAR_PAPERLESS_KEY: ${HOMEPAGE_VAR_PAPERLESS_KEY}
      HOMEPAGE_VAR_IMMICH_KEY: ${HOMEPAGE_VAR_IMMICH_KEY}
      HOMEPAGE_VAR_UNIFI_KEY: ${HOMEPAGE_VAR_UNIFI_KEY}

  dozzle-agent:
    image: amir20/dozzle:latest
    container_name: dozzle_agent_hp
    restart: unless-stopped
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
    environment:
      DOZZLE_HOSTNAME: homepage
