- Infrastructure:
    - Proxmox:
        icon: proxmox
        href: https://proxmox.infra.sintaq.net
        description: Virtualization Cluster
        siteMonitor: https://proxmox.infra.sintaq.net
        widget:
          type: proxmox
          url: https://proxmox.infra.sintaq.net
          username: "{{HOMEPAGE_VAR_PROXMOX_USERNAME}}"
          password: "{{HOMEPAGE_VAR_PROXMOX_PASSWORD}}"
          node: pve2

    - TrueNAS:
        icon: truenas
        href: https://truenas.infra.sintaq.net
        description: Network Attached Storage
        siteMonitor: https://truenas.infra.sintaq.net
        widget:
          type: truenas
          url: https://truenas.infra.sintaq.net
          version: 2
          key: "{{HOMEPAGE_VAR_TRUENAS_KEY}}"
          enablePools: true
          nasType: scale

- Network Services:
    - OPNsense:
        icon: opnsense
        href: https://opnsense.infra.sintaq.net
        description: Gateway & Firewall
        siteMonitor: https://opnsense.infra.sintaq.net
        widget:
          type: opnsense
          url: https://opnsense.infra.sintaq.net
          username: "{{HOMEPAGE_VAR_OPNSENSE_USERNAME}}"
          password: "{{HOMEPAGE_VAR_OPNSENSE_PASSWORD}}"

    - Pi-hole:
        icon: pi-hole
        href: https://pihole.infra.sintaq.net/admin/
        description: DNS & Ad-Blocking
        siteMonitor: https://pihole.infra.sintaq.net
        widget:
          type: pihole
          url: https://pihole.infra.sintaq.net
          version: 6
          key: "{{HOMEPAGE_VAR_PIHOLE_KEY}}"

    - Traefik:
        icon: traefik
        href: https://proxy.infra.sintaq.net
        description: Edge Router & Reverse Proxy
        siteMonitor: https://proxy.infra.sintaq.net
        widget:
          type: traefik
          url: https://proxy.infra.sintaq.net
          username: "{{HOMEPAGE_VAR_TRUENAS_USERNAME}}"
          password: "{{HOMEPAGE_VAR_TRUENAS_PASSWORD}}"

- App Services:
    - Paperless-ngx:
        icon: paperless-ngx
        href: https://paperless.infra.sintaq.net
        description: Document Management
        siteMonitor: https://paperless.infra.sintaq.net
        widget:
          type: paperlessngx
          url: https://paperless.infra.sintaq.net
          key: "{{HOMEPAGE_VAR_PAPERLESS_KEY}}"

    - Immich:
        icon: immich
        href: https://immich.infra.sintaq.net
        description: Photos & Videos Backup
        siteMonitor: https://immich.infra.sintaq.net
        widget:
          type: immich
          url: https://immich.infra.sintaq.net
          key: "{{HOMEPAGE_VAR_IMMICH_KEY}}"
          version: 2

    - Vaultwarden:
        icon: vaultwarden
        href: https://vaultwarden.infra.sintaq.net
        description: Password Manager
        siteMonitor: https://vaultwarden.infra.sintaq.net

- Monitoring:
    - Dozzle:
        icon: dozzle
        href: https://dozzle.infra.sintaq.net
        description: Docker Logs Viewer
        siteMonitor: https://dozzle.infra.sintaq.net
