title: Homelab | Dashboard
startUrl: https://homepage.infra.sintaq.net
background:
  brightness: 50
favicon: https://raw.githubusercontent.com/kiddyeyo/sintaqlogo/main/big_simple_logo.png
theme: dark
color: slate

layout:
  "":
    style: row
    columns: 3
  Infrastructure:
    style: row
    columns: 3
  Network Services:
    style: row
    columns: 3
  App Services:
    style: row
    columns: 3
  Monitoring:
    style: row
    columns: 1

headerStyle: clean
showStats: true
fullWidth: true
disableCollapse: true
useEqualHeights: true
hideVersion: true
disableIndexing: true
