---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- logo:
    icon: https://raw.githubusercontent.com/kiddyeyo/sintaqlogo/refs/heads/main/big_logo.png

- datetime:
    text_size: xl
    format:
      timeStyle: short
- search:
    provider: duckduckgo
    target: _blank
    showSearchSuggestions: true
    focus: true
- openmeteo:
    label: Hermosillo
    latitude: 29.07297
    longitude: -110.95592
    timezone: America/Hermosillo
    units: metric
    cache: 5
    format:
      maximumFractionDigits: 0
- openmeteo:
    label: Monterrey
    latitude: 25.6866
    longitude: -100.3161
    timezone: America/Monterrey
    units: metric
    cache: 5
    format:
      maximumFractionDigits: 0
