http:
  routers:
    dozzle-rtr:
      rule: "Host(`dozzle.infra.sintaq.net`)"
      entryPoints: ["websecure"]
      service: dozzle-svc
      tls:
        certResolver: cloudflare

  services:
    dozzle-svc:
      loadBalancer:
        servers:
          - url: "http://10.24.10.9:8080"
