http:
  routers:
    filebrowser-rtr:
      rule: "Host(`filebrowser.infra.sintaq.net`)"
      entryPoints: ["websecure"]
      service: filebrowser-svc
      tls: {}

  services:
    filebrowser-svc:
      loadBalancer:
        servers:
          - url: "http://10.24.10.12:8900"
