http:
  routers:
    homepage-rtr:
      rule: "Host(`homepage.mgmt.sintaq.net`)"
      entryPoints: ["websecure-mgmt"]
      service: homepage-svc
      tls: {}

  services:
    homepage-svc:
      loadBalancer:
        servers:
          - url: "http://10.24.10.10:3000"
