http:
  routers:
    paperless-rtr:
      rule: "Host(`paperlessngx.infra.sintaq.net`)"
      entryPoints: ["websecure"]
      service: paperlessngx-svc
      tls: {}

  services:
    paperlessngx-svc:
      loadBalancer:
        servers:
          - url: "http://10.24.10.12:8000"
