http:
  routers:
    truenas-rtr:
      rule: "Host(`truenas.infra.sintaq.net`)"
      entryPoints: ["websecure"]
      service: truenas-svc
      tls:
        certResolver: cloudflare
      middlewares: ["secure-headers"]

  services:
    truenas-svc:
      loadBalancer:
        serversTransport: insecureTransport
        servers:
          - url: "https://192.168.100.22"
