http:
  routers:
    truenas-rtr:
      rule: "Host(`truenas.infra.sintaq.net`)"
      entryPoints: ["websecure"]
      service: truenas-svc
      tls: {}

  services:
    truenas-svc:
      loadBalancer:
        serversTransport: insecureTransport
        servers:
          - url: "https://10.24.10.17"
