http:
  routers:
    vaultwarden-rtr:
      rule: "Host(`vaultwarden.infra.sintaq.net`)"
      entryPoints: ["websecure"]
      service: vaultwarden-svc
      tls:
        certResolver: cloudflare

  services:
    vaultwarden-svc:
      loadBalancer:
        servers:
          - url: "http://:80"
