---
- name: "Recrear stack de monitoring"
  ansible.builtin.command: "docker compose up -d --force-recreate --remove-orphans"
  args:
    chdir: "{{ stack_base_path }}/monitoring"
  changed_when: true
