- Infrastructure:

    - Proxmox:
        icon: proxmox
        href: https://proxmox.infra.sintaq.net
        description: Virtualization Cluster
        siteMonitor: https://proxmox.infra.sintaq.net
        widget:
          type: proxmox
          url: https://proxmox.infra.sintaq.net
          username: "${proxmox_username}" # can also be set as an environment variable
          password: "${proxmox_password}" # can also be set as an environment variable
          node: pve2

    - TrueNAS:
        icon: truenas
        href: https://truenas.infra.sintaq.net
        description: Network Attached Storage
        siteMonitor: https://truenas.infra.sintaq.net
        widget:
          type: truenas
          url: https://truenas.infra.sintaq.net
          version: 2 # optional, defaults to 1
          key: "${truenas_key}" # not required if using username / password
          enablePools: true # optional, defaults to false
          nasType: scale # defaults to scale, must be set to 'core' if using enablePools with TrueNAS Core

- Network Services:

    - OPNsense:
        icon: opnsense
        href: https://opnsense.infra.sintaq.net
        description: Gateway & Firewall
        siteMonitor: https://opnsense.infra.sintaq.net
        widget:
          type: opnsense
          url: https://opnsense.infra.sintaq.net
          username: "${opnsense_username}" # can also be set as an environment variable
          password: "${opnsense_password}" # can also be set as an environment variable

    - Pi-hole:
        icon: pi-hole
        href: https://pihole.infra.sintaq.net/admin/
        description: DNS & Ad-Blocking
        siteMonitor: https://pihole.infra.sintaq.net
        widget:
          type: pihole
          url: https://pihole.infra.sintaq.net
          version: 6 # required if running v6 or higher, defaults to 5
          key: "${pihole_key}" # optional, in v6 can be your password or app password

    - Traefik:
        icon: traefik
        href: https://proxy.infra.sintaq.net # Basado en tus headers de CORS
        description: Edge Router & Reverse Proxy
        siteMonitor: https://proxy.infra.sintaq.net
        widget:
          type: traefik
          url: https://proxy.infra.sintaq.net
          username: "${truenas_username}" # can also be set as an environment variable
          password: "${truenas_password}" # can also be set as an environment variable

- App Services:

    - Paperless-ngx:
        icon: paperless-ngx
        href: https://paperless.infra.sintaq.net
        description: Document Management
        siteMonitor: https://paperless.infra.sintaq.net
        widget:
          type: paperlessngx
          url: https://paperless.infra.sintaq.net
          key: "${paperless_key}" # can also be set as an environment variable

    - Immich:
        icon: immich
        href: https://immich.infra.sintaq.net
        description: Photos & Videos Backup
        siteMonitor: https://immich.infra.sintaq.net
        widget:
          type: immich
          url: https://immich.infra.sintaq.net
          key: "${immich_key}" # can also be set as an environment variable
          version: 2 # optional, default is 1

    - Vaultwarden:
        icon: vaultwarden
        href: https://vaultwarden.infra.sintaq.net
        description: Password Manager
        siteMonitor: https://vaultwarden.infra.sintaq.net
        server: vaultwarden
        container: vaultwarden