users:
    erickcastillo:
        email: ENC[AES256_GCM,data:cdCs8TqKJ9UTmP4RH9roMz9heCKqKydKN8o=,iv:Bdt9BD6otCXnqwnmMkZ3HxhJTyaqC/cwfP7x5lhILIo=,tag:2E8PKq86uIppUHNGpng3yQ==,type:str]
        name: ENC[AES256_GCM,data:cVPgCntZ7mDjdyjUiQ==,iv:owEANFGFYvvsIT5E6FSVWpfg9cBFbVPTOxay+RRZoZs=,tag:RkeXuyrLn8YjQMPyTyuMmw==,type:str]
        password: ENC[AES256_GCM,data:yGgbidHQg2kG1ZBOeImvnVR+SADJOEbBcJhJe1IuKRk+lbXHsdI1soP3xH9cuQH3LvQxo0Y41BDOhySf,iv:ep5h9ugp9MWYSdBRcuOVyFYJP6GjSt4vomxiWi6djAQ=,tag:GwtmSiGwSGiehZuPu6PFZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5K1Q1RjA2bVEvTm50NFRp
            cGRRaUM1UlYvMGhyNmV1Y0FqQ1BjQWVBVlFFCkJaVHpkSWFJcEJhRWxNZjlHOU9y
            NEUrQ09DZWdReCt5QUdCTEZzSExKdnMKLS0tIGVrNzNXS3JCek9WQStDcDVveWlw
            REx3U2JET1BySzhaRjVad1RrQTdKTDQKofB+EbEyY0QyUWTD08USIs93OMzjbhQS
            6lveLs6kcvCEyOJrNGKaAiWrR+Lp8uJ8rJVerDvKzyS7l2QgFfjxIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16udccp9tk379p58t0ytj5uepqjp5n0tza5q95pz2ugff55tdy4zsuj87vy
    lastmodified: "2026-06-19T07:42:32Z"
    mac: ENC[AES256_GCM,data:Dad+QE6ziTmCJT8qg4NtHyCTCO35JgQ0e0mhdTSGQVnSnLOa6nqJXufc2psKyMqDrS+abNYc+PvXnAhdYKGp0TRzZWFsXYepKziDBWaqpik2ADk8NU2uM8slWcLY1ACfsdQL1PnH5pDAEWRUrALhHKVaYYzIXUzyhxeAI4dFhRM=,iv:s0KaZKOsyNHUmVGcROodwoNvA6G+HuhReqrIZ+EazLI=,tag:yObHnFpxbZlCHuRmM5Rwpg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
