users:
    erickcastillo:
        email: ENC[AES256_GCM,data:LoplsUOQ0lZmWmVdsUVQk+pk1CKsGsOyM0Q=,iv:rFFmpXNHoib921CYGCd1gEafJu2xp649IYKu9j34qW0=,tag:4N7m2biUAB2zy0u2pMR3zQ==,type:str]
        name: ENC[AES256_GCM,data:GMzn5zkoK0E2m903ow==,iv:jVkqurL0ilXeodnmLT0LmRtZSiaeiH6zXp+dEFbobco=,tag:H7eUcpwEbvqMBDbHMBpLzQ==,type:str]
        password: ENC[AES256_GCM,data:RFgKT7c3fbgTl6dZzsM8uMBQLt1SLFsqV8ojnIjwkOwAsQr9lXCZCC3OXT2zp2v2TQqIPyt6VEvPwJm4,iv:wQNiqUYLBLcjxNKaXG+hntz8Un2UwmEOYrry/F+nRYE=,tag:1Z78lEWacL5g8O4OnUG2SA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RXRiVFpZV0wwUUhLZ1hG
            Yk5FdFp5NWF1SzZ1OW5VTTA3V0NLQitYR21VCjMveTh0M3VzMDhUS2tDVjJmMmt2
            YzNrZnZDUC9WUkFhU0dvbnBWNDVIejgKLS0tIFNzb1ZOOEc3MThJR2lsSE5kSHRv
            bkQ1dVZYc3BYbHFubUpRTStMOFhwU2sK6lzUAEWgBRtX5c/vKXgwJW7L8gMdDJxF
            Y/9PpyHaVZJFoFsKm055Q380oEzlhvTuWDSG4RnFM7hfJTIjM67K+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16udccp9tk379p58t0ytj5uepqjp5n0tza5q95pz2ugff55tdy4zsuj87vy
    lastmodified: "2026-06-19T19:25:47Z"
    mac: ENC[AES256_GCM,data:qkvcPMJj1lEqVqLV/SZrIUUPOogWPQEix2LJTkbff6phduPtne0FqA2ic1050GggSlvgCIlKEuodk0NlJ7Iwh1djw+pDnjfM00w2zf05fJeIMESmccClJwtp4d47UvfkQfXXAWefCzFD+670e+Ta2tT71gSO8UlVpAh4BHW7ga0=,iv:ccy2ijn50m6QpNU9dRLRYa3wFKQsiue6agA4NGJORgc=,tag:i3NBCOl2GKlcWL4I+HjREw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
