users:
  erickcastillo:
    email: ENC[AES256_GCM,data:TM6hSrwx6X9w/iuDqJrS+g0BCFkMeZP4Na4=,iv:oyQbMhdrvv+fy8RLQAGBck5VAMbkh87q7M9AkuQxzJo=,tag:WzRfOVqm8L8QQx/Q36gyaA==,type:str]
    name: ENC[AES256_GCM,data:YNmNIOiAgxnYqZracw==,iv:yIHxKI6sH05md4pF6ctGh2wuwAIKQjkWIcJ7EoNeMq8=,tag:rYXkeS6HQ8+FbpBiUJqCtQ==,type:str]
    password: ENC[AES256_GCM,data:woPeL1vsePzSuA+HjrhNHRH2+YYyUIu/xlOKqXtynmOmKxxfLbON56aWdtw8TagN+7XuSTbeZrxF6iEI,iv:C8g4mYXUm0B84mb7triO8uEJE05aJisYIxvigsawDBM=,tag:5IwxYFR+Ryged5XnSSXb8w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMC9UQ2RnVTlxaUhDbG1X
        Q2g4dWhCMFNoZEwwQzdEWkJwcHBhNjJoSEM0CnB1OTRFL0pKRDVVbUpyaldhcUtF
        TE4yRHFQUEdTWFdsMjJNYU5Zc1ExUVEKLS0tIEVFVEZaeVhTelZwR0k3VmlRbTlZ
        T1JJdVBZUlBqUjNTVEUraXdpNk8yZnMKHvE35L+d2n7GcCs/Bd2RrO/jg9fMoKXb
        AgatGH+RrWq+VIwT7jUpjlg7JlbaZHmKkEtZNJuxMhzWYE1SMWblzg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age16udccp9tk379p58t0ytj5uepqjp5n0tza5q95pz2ugff55tdy4zsuj87vy
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0aVFGbms0eVpGOGxuZWFj
        NjFuUjRiYWdmcmQveGd3NmpqRmcrc2xOWlRvCk9YV1RoaXNSM1l0M01wWEhZVWhk
        WTQxeE5welRaK2psdC9Wb05yYm80N28KLS0tIG0zMWt6RXZYeXZNbUFnUGE0NUd0
        RXJNQmt1QWo3QnVOc1g4emV5R1Zld0EKQuyndXksSkLE5Z8CmB1ifAkikLgg6Hwx
        iPUqU0e27Z4ZSk9kESzRLkymy9sMgvAl7t93nw7TPvapwjEvyKZwXQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17wvygazh5w2ds4xvksmd35rz2geezwgq5papqh04rj8wlhfx7ajqvmjeny
  lastmodified: "2026-06-23T00:34:29Z"
  mac: ENC[AES256_GCM,data:bvl6pE5EIQ1+HTO4gojA/Syi8muHBlgb2PvYusA6c29FMFXlfTb6ajrSRAxHHsT3y9WYQVc0vccWzrx8aNDVMsHtZ0+5FAET9yLxKdKcEgpSCnkIklYd/NFSt8CDnG9tNmWAAnwiZA6IfAOv3fKQbYLoazSeQaA2g+lViQruxyM=,iv:vJ1QMfGALF3/TbgBrqhJ89g7KkL42uVDdaaCxIhk6E4=,tag:7MuJLAKJgOJO6l25+JQJiw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
