log:
  level: DEBUG

api:
  dashboard: true

entryPoints:
  websecure:
    address: "10.24.10.8:443"
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: "infra.sintaq.net"
            sans:
              - "*.infra.sintaq.net"
    transport:
      respondingTimeouts:
        readTimeout: "0s"

  websecure-mgmt:
    address: "10.24.10.16:443"
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: "mgmt.sintaq.net"
            sans:
              - "*.mgmt.sintaq.net"
    transport:
      respondingTimeouts:
        readTimeout: "0s"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      email: castilloerick208@gmail.com
      storage: /etc/traefik/acme.json
      #      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: "10"
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
